name: Label Response

on:
  issues:
    types: [labeled]

jobs:
  comment-on-label:
    runs-on: ubuntu-latest
    steps:
    - name: Respond to label
      if: contains(github.event.label.name, 'accepted')
      run: |
        curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
          -d '{"body":"Please send an email to toolspeed@163.com to tell us your toolspeed account. We will extend your plan for three months."}'
